[2024-01-03T18:19:16.503+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509
[2024-01-03T18:19:16.505+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data'
[2024-01-03T18:19:16.585+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509
[2024-01-03T18:19:16.587+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data'
[2024-01-03T18:19:16.650+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-01-03T18:19:16.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-01-03T18:19:16.667+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2024-01-03T18:19:16.720+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-01-02 00:00:00+00:00
[2024-01-03T18:19:16.748+0000] {standard_task_runner.py:57} INFO - Started process 1156 to run task
[2024-01-03T18:19:16.752+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'load_data', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpb7yh6mox']
[2024-01-03T18:19:16.756+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask load_data
[2024-01-03T18:19:16.867+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509
[2024-01-03T18:19:16.868+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data'
[2024-01-03T18:19:16.872+0000] {task_command.py:415} INFO - Running <TaskInstance: booking_ingestion.load_data scheduled__2024-01-02T00:00:00+00:00 [running]> on host 7bf68de21308
[2024-01-03T18:19:17.300+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='booking_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-01-03T18:19:17.329+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-03T18:19:17.388+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_operator.py", line 93, in load_data
    cursor.execute(insert_data_query,tuple(row.values))
psycopg2.errors.NumericValueOutOfRange: integer out of range

[2024-01-03T18:19:17.411+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=booking_ingestion, task_id=load_data, execution_date=20240102T000000, start_date=20240103T181916, end_date=20240103T181917
[2024-01-03T18:19:17.467+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task load_data (integer out of range
; 1156)
[2024-01-03T18:19:17.488+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-03T18:19:17.532+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-03T19:58:29.127+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509
[2024-01-03T19:58:29.141+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data'
[2024-01-03T19:58:29.228+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509
[2024-01-03T19:58:29.229+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data'
[2024-01-03T19:58:29.294+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-01-03T19:58:29.312+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2024-01-03T19:58:29.313+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2024-01-03T19:58:29.352+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-01-02 00:00:00+00:00
[2024-01-03T19:58:29.361+0000] {standard_task_runner.py:57} INFO - Started process 3705 to run task
[2024-01-03T19:58:29.365+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'load_data', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmponydgsvd']
[2024-01-03T19:58:29.371+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask load_data
[2024-01-03T19:58:29.464+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509
[2024-01-03T19:58:29.466+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=booking_ingestion/run_id=scheduled__2024-01-02T00:00:00+00:00/task_id=load_data'
[2024-01-03T19:58:29.469+0000] {task_command.py:415} INFO - Running <TaskInstance: booking_ingestion.load_data scheduled__2024-01-02T00:00:00+00:00 [running]> on host 7bf68de21308
[2024-01-03T19:58:29.858+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='booking_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2024-01-03T19:58:29.885+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-03T19:58:29.937+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_operator.py", line 99, in load_data
    cursor.execute(query, tuple(row_dict.values()))
psycopg2.errors.NumericValueOutOfRange: integer out of range

[2024-01-03T19:58:29.951+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=booking_ingestion, task_id=load_data, execution_date=20240102T000000, start_date=20240103T195829, end_date=20240103T195829
[2024-01-03T19:58:29.998+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task load_data (integer out of range
; 3705)
[2024-01-03T19:58:30.023+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-03T19:58:30.098+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
