[2024-01-02T14:38:48.047+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-02T14:38:48.092+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-02T14:38:48.093+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-01-02T14:38:48.228+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-01-01 00:00:00+00:00
[2024-01-02T14:38:48.249+0000] {standard_task_runner.py:57} INFO - Started process 376 to run task
[2024-01-02T14:38:48.263+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpbstdhzxh']
[2024-01-02T14:38:48.270+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask create_postgres_table
[2024-01-02T14:38:48.386+0000] {task_command.py:415} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table scheduled__2024-01-01T00:00:00+00:00 [running]> on host ce0bd5f35f4e
[2024-01-02T14:38:49.762+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v01' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-02T14:38:49.765+0000] {sql.py:274} INFO - Executing: 
        create table if not exists booking_record(
            client_id int,
            booking_date date,
            room_type varchar(250),
            hotel_id int,
            booking_cost decimal(10,1),
            currency varchar(50)
        )
    
[2024-01-02T14:38:49.806+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-01-02T14:38:49.869+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20240101T000000, start_date=20240102T143848, end_date=20240102T143849
[2024-01-02T14:38:50.085+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 376)
[2024-01-02T14:38:50.164+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T14:38:50.300+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
