[2024-01-02T19:29:14.812+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-01T19:28:41.770648+00:00 [queued]>
[2024-01-02T19:29:14.859+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-01T19:28:41.770648+00:00 [queued]>
[2024-01-02T19:29:14.860+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-02T19:29:14.945+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-01-01 19:28:41.770648+00:00
[2024-01-02T19:29:14.981+0000] {standard_task_runner.py:57} INFO - Started process 2764 to run task
[2024-01-02T19:29:14.988+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'load_data', 'scheduled__2024-01-01T19:28:41.770648+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgress_operator2.py', '--cfg-path', '/tmp/tmp74_dmgw9']
[2024-01-02T19:29:14.995+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask load_data
[2024-01-02T19:29:15.210+0000] {task_command.py:415} INFO - Running <TaskInstance: booking_ingestion.load_data scheduled__2024-01-01T19:28:41.770648+00:00 [running]> on host ce0bd5f35f4e
[2024-01-02T19:29:18.842+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='booking_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T19:28:41.770648+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T19:28:41.770648+00:00'
[2024-01-02T19:29:18.848+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgress_operator2.py", line 60, in load_data
    postgres_hook = PostgresHook(postgres_localhost)
NameError: name 'postgres_localhost' is not defined
[2024-01-02T19:29:18.975+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=load_data, execution_date=20240101T192841, start_date=20240102T192914, end_date=20240102T192918
[2024-01-02T19:29:19.164+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task load_data (name 'postgres_localhost' is not defined; 2764)
[2024-01-02T19:29:19.419+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T19:29:19.446+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
