[2024-01-02T19:25:01.375+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-01T19:23:53.566471+00:00 [queued]>
[2024-01-02T19:25:01.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion.load_data scheduled__2024-01-01T19:23:53.566471+00:00 [queued]>
[2024-01-02T19:25:01.399+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-02T19:25:01.905+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-01-01 19:23:53.566471+00:00
[2024-01-02T19:25:02.007+0000] {standard_task_runner.py:57} INFO - Started process 2592 to run task
[2024-01-02T19:25:02.012+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'load_data', 'scheduled__2024-01-01T19:23:53.566471+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgress_operator2.py', '--cfg-path', '/tmp/tmpj5rbuw21']
[2024-01-02T19:25:02.017+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask load_data
[2024-01-02T19:25:03.262+0000] {task_command.py:415} INFO - Running <TaskInstance: booking_ingestion.load_data scheduled__2024-01-01T19:23:53.566471+00:00 [running]> on host ce0bd5f35f4e
[2024-01-02T19:25:13.491+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='booking_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T19:23:53.566471+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T19:23:53.566471+00:00'
[2024-01-02T19:25:13.498+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgress_operator2.py", line 60, in load_data
    postgres_hook = PostgresHook(postgres_localhost)
NameError: name 'postgres_localhost' is not defined
[2024-01-02T19:25:13.745+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=load_data, execution_date=20240101T192353, start_date=20240102T192501, end_date=20240102T192513
[2024-01-02T19:25:14.698+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task load_data (name 'postgres_localhost' is not defined; 2592)
[2024-01-02T19:25:14.726+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-02T19:25:14.752+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
